services:
  db:
    image: mysql:8.4.3
    volumes:
      - onair-db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - onair-overlay-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  onair-db-data:

networks:
  onair-overlay-network:
    driver: overlay
    attachable: true
    name: onair-overlay-network